services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: LES
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: speltamatheus/les:latest
    ports:
      - "5021:5020"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/LES
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      PRINTER_NAME: Termica
    extra_hosts:
      - "host.docker.internal:host-gateway"
    devices:
        - "/dev/usb/lp0:/dev/usb/lp0"
    privileged: true

volumes:
  postgres_data: { }

networks:
  app-network:
    driver: bridge